

# # 1. Empty
# def f1(): ...


# # 2. Only positional-or-keyword
# def f2(a, b, c): ...


# # 3. With defaults
# def f3(a, b=2, c=3): ...


# # 4. Positional-only (with /)
# def f4(a, b, /): ...
# def f5(a, b=1, /): ...


# # 5. Mix of positional-only + regular
# def f6(a, b, /, c, d): ...
# def f7(a, b=1, /, c, d=2): ...

# # 6. Var-positional (*args)
# def f8(*args): ...
# def f9(a, *args): ...
# def f10(a, b=2, *args): ...


# # 7. Keyword-only (bare *)
# def f11(*, x, y): ...
# def f12(a, *, x=1, y=2): ...


# # 8. Keyword-only (after *args)
# def f13(*args, x, y): ...
# def f14(a, *args, x=1, y=2): ...

# # 9. Var-keyword (**kwargs)
# def f15(**kwargs): ...
# def f16(a, **kwargs): ...
# def f17(*args, **kwargs): ...
# def f18(a, *args, **kwargs): ...
# def f19(a, b=1, *args, x, y=2, **kwargs): ...
# def f20(a, b=1, /, c=2, *args, x, y=3, **kwargs): ...
# # 10. Positional-only + var-positional + keyword-only + var-keyword
# def f21(a, b=1, /, *args, x, y=2, **kwargs): ...


# # 11. Full combination
# def f(a, b=1, /, d=2, *args, e, f=3, **kwargs): 
#     print('a:', a)
#     print('b:', b)
#     print('d:', d)
#     print('args:', args)
#     print('e:', e)
#     print('f:', f)
#     print('kwargs:', kwargs)

# f(10, 20, 30, 40, 50, e=60, f=70, g=80, h=90)
# def f7(a, b=1, /, c, d=2): 
#     return a, b, c, d

# print(f7(10, 20, 30))

# def f7(a, /, b=1, c, d=2): ...


code = '''
def foo(a, b=1, /, d=2, *args, e, f=3, **kwargs):... 
'''

import ast
ast_obj = ast.parse(code)
print(ast.dump(ast_obj, indent=4))